### ISSUE TITLE
Version 1.2.0 breaks config:cache command

### ISSUE THREAD

**Issue by bobab12** [consilience/laravel-extended-logging#5]
First of all, thanks for this very useful package.

After upgrading to version 1.2.0, `artisan config:cache` fails with the following error:

```
LogicException 

  Your configuration files are not serializable.

  at vendor/laravel/framework/src/Illuminate/Foundation/Console/ConfigCacheCommand.php:71
     67▕             require $configPath;
     68▕         } catch (Throwable $e) {
     69▕             $this->files->delete($configPath);
     70▕ 
  ➜  71▕             throw new LogicException('Your configuration files are not serializable.', 0, $e);
     72▕         }
     73▕ 
     74▕         $this->info('Configuration cached successfully!');
     75▕     }

  1   bootstrap/cache/config.php:749
      Error::("Call to undefined method Consilience\Laravel\ExtendedLogging\Processor\AuthUserProcessor::__set_state()")

      +14 vendor frames 
  16  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```

This seems to be related to the change in pull request #4, allowing processors to be configured in the `laravel-extended-logging.php` config file. Referencing non-serializable objects in config files prevents the configs from being cacheable.

FWIW: in order to customize the processors, what worked for me in the previous version was to simply provide a custom `Consilience\Laravel\ExtendedLogging\Tap` implementation and reference that in the `logging.php` config file.

**Comment by judgej** [comment]
Thanbl you for this, I'll aim to look at it later today. From what I memember reading on soem Laravel upgrade notes, it is closures that cannot be cached. I guess it's class instantiation too. Would replacing them with the FQDN as a string solve that, with options supplied in some other way?

    new PsrLogMessageProcessor,
    new UidProcessor(Tap::UID_LENGTH),

becomes maybe:

    PsrLogMessageProcessor::class,
    UidProcessor::class => [Tap::UID_LENGTH],

or:

    PsrLogMessageProcessor::class,
    [
        UidProcessor::class,
        Tap::UID_LENGTH,
    ],

Or is it something else?

**Comment by bobab12** [comment]
Great, thanks! :+1: 

Yeah, unless those classes implement `__set_state()` it appears. I just noticed the following error while diving into it a bit deeper:

```
In config.php line 749:

  Call to undefined method Consilience\Laravel\ExtendedLogging\Processor\AuthUserProcessor::__set_state()
```

Replacing them with FQDN looks like a good solution to me as well. Just tested and can confirm that caching works. Not sure which array format is best though. The first option presented looks aesthetically better in my opinion.

**Comment by judgej** [comment]
Going to sleep on this tonight. Was wonderign about the best way to cache the instantiated processing classes. I could just put them into a static var in `Consilience\Laravel\ExtendedLogging\Tap`, or they could go into the laravel container. Or could the classes be made serialisable, so once instantiated as the config file is loaded, is is that instantiated class that is cached. I mean, it's definetly not a colosure.

**Comment by judgej** [comment]
Release 1.3.0 tagged with this fix. Tried it for a few days on various apps and works fine for us.

**Comment by bobab12** [comment]
Awesome. Just tried upgrading and appears to be working for me as well. Thanks so much!

**Comment by judgej** [comment]
Cool, thank you for raising this. I'm going to have to test this on Laravel 9 now, since that is imminent this month. Never stops :-)
